services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: auction_db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data-auction:rw
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  db-data: {}
  redis:
    driver: local
